In [2]:
from IPython.display import display as dsp
import numpy as np

In [3]:
A = np.array([[2, 1, 1], [1, 0, 2], [1, 2, 0]])
b1 = np.array([1, 1, 0])
b2 = np.array([1, 0, 1])
b3 = np.array([1, 1, 1])

dsp(np.linalg.det(A))

dsp(np.hstack((A, np.array([b1]).T, np.array([b2]).T, np.array([b3]).T)))

dsp(np.linalg.solve(A, b1))
dsp(np.linalg.solve(A, b2))
dsp(np.linalg.solve(A, b3))

np.float64(-4.0)

array([[2, 1, 1, 1, 1, 1],
       [1, 0, 2, 1, 0, 1],
       [1, 2, 0, 0, 1, 1]])

array([ 0.5 , -0.25,  0.25])

array([ 0.5 ,  0.25, -0.25])

array([0. , 0.5, 0.5])

In [4]:
A = np.array([[2, 4, 8], [-1, 1, -1], [3, 2, 8]])

dsp(A)

dsp(np.linalg.det(A))

for row in A:
    print(row, end=' ')
print('Do not span R3')

array([[ 2,  4,  8],
       [-1,  1, -1],
       [ 3,  2,  8]])

np.float64(0.0)

[2 4 8] [-1  1 -1] [3 2 8] Do not span R3


In [5]:
# DETERMINE WHETHER THE GIVEN POLYNOMIALS SPAN P2

A = np.array([
    [1, -1, 2],
    [3, 1, 0],
    [5, -1, 4],
    [-2, -2, 2]
]).T

dsp(A)

array([[ 1,  3,  5, -2],
       [-1,  1, -1, -2],
       [ 2,  0,  4,  2]])

In [6]:
A = np.matrix([
    [1, 1, 0, 0],
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [0, 0, 1, 1]
])

dsp(np.linalg.det(A))

# does not span M22

np.float64(0.0)

In [7]:
def is_row_echelon_form(matrix): 
	if not matrix.any(): 
		return False

	rows = matrix.shape[0] 
	cols = matrix.shape[1] 
	prev_leading_col = -1

	for row in range(rows): 
		leading_col_found = False
		for col in range(cols): 
			if matrix[row, col] != 0: 
				if col <= prev_leading_col: 
					return False
				prev_leading_col = col 
				leading_col_found = True
				break
		if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)): 
			return False
	return True

def find_nonzero_row(matrix, pivot_row, col): 
	nrows = matrix.shape[0] 
	for row in range(pivot_row, nrows): 
		if matrix[row, col] != 0: 
			return row 
	return None

# Swapping rows so that we can have our non zero row on the top of the matrix 
def swap_rows(matrix, row1, row2): 
	matrix[[row1, row2]] = matrix[[row2, row1]] 

def make_pivot_one(matrix, pivot_row, col): 
	pivot_element = matrix[pivot_row, col] 
	matrix[pivot_row] //= pivot_element 
	# print(pivot_element) 

def eliminate_below(matrix, pivot_row, col): 
	nrows = matrix.shape[0] 
	pivot_element = matrix[pivot_row, col] 
	for row in range(pivot_row + 1, nrows): 
		factor = matrix[row, col] 
		matrix[row] -= factor * matrix[pivot_row] 

# Implementing above functions 
def row_echelon_form(matrix): 
	nrows = matrix.shape[0] 
	ncols = matrix.shape[1] 
	pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times 
	for col in range(ncols): 
		nonzero_row = find_nonzero_row(matrix, pivot_row, col) 
		if nonzero_row is not None: 
			swap_rows(matrix, pivot_row, nonzero_row) 
			make_pivot_one(matrix, pivot_row, col) 
			eliminate_below(matrix, pivot_row, col) 
			pivot_row += 1
	return matrix 

def REF(matrix: np.array):
    print("Matrix Before Converting:") 
    print(matrix) 
    print() 
    result = row_echelon_form(matrix) 
    print("After Converting to Row Echelon Form:") 
    print(result) 
    if is_row_echelon_form(result): 
        print("In REF") 
    else: 
        print("Not in REF--------------->")

REF(np.array([[0, 6, 4], [3, 0, -7], [1, 5, 1], [-1, 1, 3]]))

Matrix Before Converting:
[[ 0  6  4]
 [ 3  0 -7]
 [ 1  5  1]
 [-1  1  3]]

After Converting to Row Echelon Form:
[[ 1  0 -3]
 [ 0  1  0]
 [ 0  0  1]
 [ 0  0  0]]
In REF


In [19]:
def sqrt(n: int) -> int:
    def search(l: float, r: float):
        mid = (r + l) / 2

        midsq = mid*mid
        if int(midsq) == n:
            return mid
        elif midsq < n:
            return search(mid, r)
        else:
            return search(l, mid)
    return int(search(0, n))

sqrt(8)

2

In [20]:
np.linalg.det([[3, 0, 0, 1], [6, -1, -8, 0], [3, -1, -12, -1], [-6, 0, -4, 2]])

np.float64(47.999999999999986)

In [46]:
prec = {
    '+': 1, '-': 1,
    '*': 2, '/': 2,
    '(': 0, ')': 0
}

def postfix(infix: str) -> str:
    s = []
    res = ''

    for c in infix:
        if c == ' ':
            continue
        if c.isalnum():
            res += c
        elif c == '(':
            s.append(c)
        elif c == ')':
            while s and s[-1] != '(':
                res += s.pop()
            s.pop()
        else:
            while s and prec[c] <= prec[s[-1]]:
                res += s.pop()
            s.append(c)
        
    while s:
        res += s.pop()
    return res

def prefix(infix: str) -> str:
    return postfix(''.join(')' if c == '(' else '(' if c  == ')' else c for c in infix[::-1]))[::-1]

print(postfix(' x + ((x*y + x) / y)'))
print(prefix(' x + ((x*y + x) / y)'))


xxy*x+y/+
+x/+*xyxy
