In [695]:
import numpy as np
from IPython.display import display as printf

In [8]:
x = [1, 2, 3]
np.array(x)

array([1, 2, 3])

In [9]:
x_m = [x, x, x]
np.array(x_m)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
# kinda like range but this one generates an array
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [31]:
# used to generate a 0 matrix
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
# used to generate a matrix with all 1s
# (you can also specifiy types for both .zeroes and .ones)
np.ones((5, 5), dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [160]:
# generating linearly spaced n values from an interval
# in this case 13 values from [0, 4]
np.round(np.linspace(0, 4, 13), 2) # this
# or...
np.linspace(0, 4, 13).round(2)

array([0.  , 0.33, 0.67, 1.  , 1.33, 1.67, 2.  , 2.33, 2.67, 3.  , 3.33,
       3.67, 4.  ])

In [73]:
# used to generate the eye-dentity matrix XD
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
# used to generate n^m values over a uniform distribution from [0, 1)
# n = values
# m = dimensions (different args)
np.random.rand(2, 2)

array([[0.57237741, 0.3696612 ],
       [0.08870262, 0.34317067]])

In [93]:
# used to generate from a normal distribution of sigma = 1
# values closer to 0 are more likely to appear because of the nature of the distribution
np.random.randn(2, 2)

array([[ 1.2563981 ,  0.39353752],
       [ 0.29376238, -0.74485945]])

In [99]:
# returns n random values between provided interval [a, b)
np.random.randint(0, 10, 10)

array([7, 1, 6, 4, 9, 8, 8, 0, 7, 8], dtype=int32)

In [125]:
# seed is used to generate the same random results
np.random.seed(10)
np.random.randint(1, 11, 10)

array([10,  5,  1,  2, 10,  1,  2,  9, 10,  1], dtype=int32)

In [159]:
# re shapes the array (as the name suggests)
np.random.seed(10)
np.random.randint(1, 10, 25).reshape((5, 5)) # this
# or...
np.reshape(np.random.randint(1, 10, 25), (5, 5))

array([[5, 3, 7, 8, 9],
       [9, 3, 1, 7, 8],
       [9, 2, 8, 2, 5],
       [1, 9, 6, 5, 8],
       [9, 9, 3, 7, 3]], dtype=int32)

In [203]:
rarr = np.random.randint(1, 10, 16).reshape(4, 4)
print(f'max: {rarr.max()} at axis = 0: {rarr.argmax(axis=0)}, axis = 1: {rarr.argmax(axis=1)}')
print(f'min: {rarr.min()} at axis = 0: {rarr.argmin(axis=0)}, axis = 1: {rarr.argmin(axis=1)}')

print(rarr[1:-1, 1:-1])
print(rarr[0, -1])

rarr

max: 9 at axis = 0: [2 0 3 3], axis = 1: [1 2 0 3]
min: 1 at axis = 0: [0 2 0 0], axis = 1: [0 0 1 1]
[[3 5]
 [2 4]]
1


array([[1, 4, 2, 1],
       [1, 3, 5, 3],
       [8, 2, 4, 6],
       [5, 2, 8, 9]], dtype=int32)

In [213]:
# array splicing returns a mutable window which changes the original array
# applying a single value over a window is called broadcasting
rarr[0:, :1] = 0
rarr

array([[0, 4, 2, 1],
       [0, 3, 5, 3],
       [0, 2, 4, 6],
       [0, 2, 8, 9]], dtype=int32)

In [266]:
# vals can be conditionally selected from a window or the entire array itself
vals = np.linspace(0, 4, 12).reshape(4, 3).round(3)
print(vals[:2][(vals[:2] > 1) | (vals[:2] < 0.5)])
vals

[0.    0.364 1.091 1.455 1.818]


array([[0.   , 0.364, 0.727],
       [1.091, 1.455, 1.818],
       [2.182, 2.545, 2.909],
       [3.273, 3.636, 4.   ]])

In [288]:
# operations can be performed on all values of the array
print(np.arange(1, 10, 2)**3)
print((np.arange(1, 10, 2) + np.arange(0, 10, 2) - 1)**2)

[  1  27 125 343 729]
[  0  16  64 144 256]


In [349]:
rarr = np.random.randint(0, 10, 20).reshape(10, 2)
print(f'sum = {rarr.sum()}, axis = 0: {rarr.sum(axis=0)}, axis = 1: {rarr.sum(axis=1)}')
print(f'mean = {rarr.mean()}, axis = 0: {rarr.mean(axis=0)}, axis = 1: {rarr.mean(axis=1)}')

rarr

sum = 91, axis = 0: [47 44], axis = 1: [12 11  7  7  4  5 10 15 11  9]
mean = 4.55, axis = 0: [4.7 4.4], axis = 1: [6.  5.5 3.5 3.5 2.  2.5 5.  7.5 5.5 4.5]


array([[8, 4],
       [6, 5],
       [2, 5],
       [1, 6],
       [0, 4],
       [2, 3],
       [9, 1],
       [7, 8],
       [4, 7],
       [8, 1]], dtype=int32)

In [351]:
myarray = np.linspace(0, 10, 101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [520]:
dice_rolls = np.random.randint(1, 7, 10)
print(dice_rolls[dice_rolls > 2])
dice_rolls

[4 4 3 3 3 6]


array([4, 1, 2, 4, 2, 3, 3, 3, 1, 6], dtype=int32)

In [576]:
# used to bind a function as a universal numpy array
# takes 3 params:
# function, number of input params, output values

add2_1 = np.frompyfunc(lambda x, y: x+y, 2, 1)
add2_2 = np.frompyfunc(lambda x, y: (x*2, x+y), 2, 2)

print(add2_1(np.arange(1, 10, 2), np.arange(0, 10, 2)))
add2_2(np.arange(5, 9).reshape(2, 2), np.arange(0, 4).reshape(2, 2))

[1 5 9 13 17]


(array([[10, 12],
        [14, 16]], dtype=object),
 array([[5, 7],
        [9, 11]], dtype=object))

In [604]:
# kinda like frompyfunc but it's mainly used to loop over a parameter

sub = np.vectorize(lambda x, y: x-y if x > y else x)
sub([10, 2, 3, 4], -2)

array([12,  4,  5,  6])

In [623]:
# frompyfunc can also be used as a map over numpy arrays

np.array(list(map(str, np.arange(1, 10, 2))))
np.frompyfunc(str, 1, 1)(np.arange(1, 10, 2))

array(['1', '3', '5', '7', '9'], dtype=object)

In [678]:
# numpy operator functions

np.random.seed(10)

ten_rolls = lambda: np.random.randint(1, 7, 10)

rolls1, rolls2 = [np.random.randint(1, 7, 10) for _ in range(2)]
print(f'first: {rolls1}')
print(f'second: {rolls2}')
print()
print(f'add: {np.add(rolls1, rolls2)}')
print(f'sub: {np.subtract(rolls1, rolls2)}')
print(f'mul: {np.multiply(rolls1, rolls2)}')
print(f'div: {np.divide(rolls1, rolls2)}')
print(f'pow: {np.pow(rolls1, rolls2)}')
print(f'mod: {np.mod(rolls1, rolls2)}')
print('divmod: ', *np.divmod(rolls1, rolls2))
print(f'abs: {np.abs(rolls1)} {np.abs(rolls2)}')

first: [2 6 5 1 2 4 5 2 6 1]
second: [6 2 3 1 2 1 3 1 5 4]

add: [ 8  8  8  2  4  5  8  3 11  5]
sub: [-4  4  2  0  0  3  2  1  1 -3]
mul: [12 12 15  1  4  4 15  2 30  4]
div: [0.33333333 3.         1.66666667 1.         1.         4.
 1.66666667 2.         1.2        0.25      ]
pow: [  64   36  125    1    4    4  125    2 7776    1]
mod: [2 0 2 0 0 0 2 0 1 1]
divmod:  [0 3 1 1 1 4 1 2 1 0] [2 0 2 0 0 0 2 0 1 1]
abs: [2 6 5 1 2 4 5 2 6 1] [6 2 3 1 2 1 3 1 5 4]


In [723]:
# numpy functions that deal with decimals
rarr = np.random.randn(5) * 10

printf(rarr)

print(f'trunc: {np.trunc(rarr)}')
print(f'round: {np.around(rarr)}')
print(f'ceil : {np.ceil(rarr)}') 
print(f'floor: {np.floor(rarr)}') 

array([-21.31712108,  -0.48830511,   3.93341217,   2.17265145,
       -19.9439377 ])

trunc: [-21.  -0.   3.   2. -19.]
round: [-21.  -0.   4.   2. -20.]
ceil : [-21.  -0.   4.   3. -19.]
floor: [-22.  -1.   3.   2. -20.]


In [751]:
# numpy also provides set like functionality

rarr1, rarr2 = [np.random.randint(0, 5, 5) for _ in range(2)]
printf(rarr1, rarr2)

print(f'unqiue: {np.unique(rarr1)} {np.unique(rarr2)}')
print(f'union: {np.union1d(rarr1, rarr2)}')
print(f'intersect: {np.intersect1d(rarr1, rarr2)}')
print(f'diff: {np.setdiff1d(rarr1, rarr2)}')

array([0, 4, 1, 4, 2], dtype=int32)

array([1, 1, 4, 3, 3], dtype=int32)

unqiue: [0 1 2 4] [1 3 4]
union: [0 1 2 3 4]
intersect: [1 4]
diff: [0 2]


In [813]:
# you can also use numpy to find the gcd of two numbers
num1, num2 = np.random.randint(1, 100), np.random.randint(1, 100)
print(f'num1 = {num1}, num2 = {num2}, gcd = {np.gcd(num1, num2)}, lcm = {np.lcm(num1, num2)}')

rarr = np.random.randint(1, 100, 10)
print(f'rarr: {rarr}, gcd = {np.gcd.reduce(rarr)}, lcm = {np.lcm.reduce(rarr)}')

num1 = 81, num2 = 24, gcd = 3, lcm = 648
rarr: [85 10 83 25 45 59 92 91 89 34], gcd = 1, lcm = -238421268


In [829]:
# used to find difference between current and next value. can be performed n times
rarr = np.random.randint(0, 10, 3)
printf(rarr)
printf(np.diff(rarr))
np.diff(rarr, 2)

array([3, 8, 7], dtype=int32)

array([ 5, -1], dtype=int32)

array([-6], dtype=int32)

In [926]:
printf(np.random.normal(loc=0, scale=10))
printf(np.random.binomial(5, 0.5, 10))
printf(np.random.poisson(3, 10))
printf(np.random.uniform(1, 10, 1))
printf(np.random.logistic(1, 10, (2, 1)))

-0.5188412362969472

array([2, 4, 3, 1, 2, 1, 3, 2, 3, 4], dtype=int32)

array([2, 4, 6, 3, 3, 1, 6, 6, 1, 4], dtype=int32)

array([2.06625835])

array([[-17.12229449],
       [  9.60240127]])