In [15]:
import numpy as np
from IPython.display import display


np.arange(20, 50, 2)[1:]

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [35]:
arr = np.arange(1, 19, 2).reshape((3, 3))

for row in np.nditer(arr):
    print(row)

1
3
5
7
9
11
13
15
17


In [49]:
display(np.multiply(4 * np.arange(2, 20, 2).reshape((3, 3)), np.eye(3)))
display(np.matmul(4 * np.arange(2, 20, 2).reshape((3, 3)), np.eye(3)))

array([[ 8.,  0.,  0.],
       [ 0., 40.,  0.],
       [ 0.,  0., 72.]])

array([[ 8., 16., 24.],
       [32., 40., 48.],
       [56., 64., 72.]])

In [53]:
students = np.array([
    ('Fasih', 5.5, 10),
    ('Owais', 5.5, 11),
    ('Abser', 5.8, 9),
    ('Ali', 5.8, 10)
], dtype=[('name', '<U10'), ('height', '<f4'), ('class', '<i8')])


np.sort(students, order=['class', 'height'])

array([('Abser', 5.8,  9), ('Fasih', 5.5, 10), ('Ali', 5.8, 10),
       ('Owais', 5.5, 11)],
      dtype=[('name', '<U10'), ('height', '<f4'), ('class', '<i8')])

In [68]:
rarr = np.random.choice([2, 5, 9, 10], (4, 4))
odd = np.arange(1, 33, 2).reshape((4, 4))
display(np.matmul(rarr, np.eye(4)) + odd)
display(np.multiply(rarr, np.eye(4)) + odd)

array([[ 6.,  8., 14., 12.],
       [18., 21., 22., 25.],
       [27., 28., 26., 25.],
       [30., 36., 38., 36.]])

array([[ 6.,  3.,  5.,  7.],
       [ 9., 21., 13., 15.],
       [17., 19., 26., 23.],
       [25., 27., 29., 36.]])

In [71]:
mat1 = np.random.randint(0, 20, (5, 3))
mat2 = np.random.randint(0, 20, (3, 2))

np.matmul(mat1, mat2)


array([[255, 379],
       [161, 253],
       [348, 529],
       [112, 179],
       [424, 611]], dtype=int32)

In [78]:
nums = np.random.randint(0, 100, 1000)

with open('info.txt', 'w+') as f:
    vals = [
        f'average = {nums.mean()}\n',
        f'variance = {nums.var()}\n',
        f'standard_deviation = {nums.std()}',
    ]

    f.writelines(vals)
    print(''.join(vals))

average = 51.776
 variance = 880.675824
 standard_deviation = 29.676182773395908
