In [218]:
import numpy as np
from IPython.display import display

np.random.seed(20)

#### Q1

In [219]:
arr = np.random.randint(1, 11, 5)

display(arr)

print(f'Sum: {arr.sum()}')
print(f'Mean: {arr.mean()}')
print(f'Product: {arr.prod()}')

array([ 4, 10,  5,  7,  8], dtype=int32)

Sum: 34
Mean: 6.8
Product: 11200


#### Q2

In [220]:
mat = np.random.randint(-10, 10, (3, 3))

display(mat)
display(mat.T)

array([[ -8, -10,  -2],
       [  9,   6,  -4],
       [ -4,   6,  -1]], dtype=int32)

array([[ -8,   9,  -4],
       [-10,   6,   6],
       [ -2,  -4,  -1]], dtype=int32)

#### Q3

In [221]:
np.random.randint(-10, 10, 20).reshape(4, 5)

array([[ -5,  -3,  -5,  -8,  -4],
       [  3,   1,  -7,   0,   1],
       [  3,   9,   4, -10,   0],
       [  1,  -4,   1,   8,  -7]], dtype=int32)

#### Q4

In [222]:
arr1, arr2 = np.array([1, 3, 5, 7, 9]), np.array([2, 4, 6, 8, 10])

display(arr1 + arr2)
display(arr1 - arr2)
display(arr1 * arr2)
display(arr1 / arr2)

array([ 3,  7, 11, 15, 19])

array([-1, -1, -1, -1, -1])

array([ 2, 12, 30, 56, 90])

array([0.5       , 0.75      , 0.83333333, 0.875     , 0.9       ])

#### Q5

In [223]:
from math import sqrt

arr1 = np.random.randint(0, 100, 10)
sqrt_vec = np.frompyfunc(lambda a: sqrt(a), 1, 1)

arr = sqrt_vec(arr1).astype(np.float32).round(2)

display(arr1)
arr

array([77, 17, 43, 16, 18, 79, 90, 59, 71, 75], dtype=int32)

array([8.77, 4.12, 6.56, 4.  , 4.24, 8.89, 9.49, 7.68, 8.43, 8.66],
      dtype=float32)

#### Q6

In [224]:
mat = np.random.randint(0, 10, (2, 2))

display(mat)
print(f'det(mat): {np.linalg.det(mat)}')
display(np.linalg.inv(mat))

array([[6, 6],
       [8, 2]], dtype=int32)

det(mat): -36.0


array([[-0.05555556,  0.16666667],
       [ 0.22222222, -0.16666667]])

#### Q7

In [225]:
arr = np.random.randint(-10, 10, 50)

display(arr)

print(f'Minimum index: {arr.argmin()}')
print(f'Maximum index: {arr.argmax()}')

array([ -9,   4,   0,  -7,   8,  -4,  -1,   4,  -6,   1,  -2,  -4,   5,
         8,   4,   9,   0,   0,  -9,   8,   7,  -2,   8,   0,  -6,  -2,
         6,   9,   6,   0,  -4,  -1, -10,   2,   4,   7,  -1,  -4,   0,
        -3,  -1,  -1,   4,   5,   8,   2,   0,   8,   7,   2], dtype=int32)

Minimum index: 32
Maximum index: 15


#### Q8

In [226]:
A = np.array([[2, 4], [1, 1]])
b = np.array([16, 7])

np.linalg.solve(A, b)

array([6., 1.])

#### Q9

In [227]:
arr = np.random.randint(-10, 10, 25)

display(arr)
np.percentile(arr, 75)

array([ -5,  -8,  -5,  -1,  -1,  -8,   5,  -9,   7,   6,  -2,   1,  -5,
       -10,  -5,  -6,   1,   8,  -1,   4,  -5,  -7,   1,  -1,  -9],
      dtype=int32)

np.float64(1.0)

#### Q10

In [228]:
def normalize(arr: np.array):
    return (arr - arr.mean()) / arr.std()

arr = np.random.randint(1, 10, 5)
display(arr)
normalize(arr)

array([3, 4, 7, 6, 5], dtype=int32)

array([-1.41421356, -0.70710678,  1.41421356,  0.70710678,  0.        ])