In [778]:
from IPython.display import display
import pandas as pd
import numpy as np

In [779]:
# given a matrix, surround it by zeroes

arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

n, m = arr.shape
zeros = np.zeros((n+2, m+2))
zeros[1:-1, 1:-1] = arr
zeros

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 5., 6., 0.],
       [0., 0., 0., 0.]])

In [780]:
# circular shift a matrix

arr = np.array([1, 2, 3, 4, 5])
k = 2

np.roll(arr, k)

array([4, 5, 1, 2, 3])

In [781]:
arr = np.array([1, 2, 3, 4])

display(np.insert(arr, 1, [5, 6, 7, 8]))
display(np.append(arr, [5, 6, 7, 8]))

array([1, 5, 6, 7, 8, 2, 3, 4])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [782]:
# for the given 2 arrays, find the intersection, union, and difference of their rows

arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[3, 4], [7, 8]])

In [783]:
# solve a linear system

A = np.array(
    [[1, 1],
    [1, 2]]
)
b = np.array([9, 8])

np.matmul(np.matrix(A).I, b)

matrix([[10., -1.]])

In [784]:
display(np.eye(3))
display(np.eye(3, 2))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [785]:
first_row = np.array([1, 2, 3])
first_col = np.array([1, 4, 5])


m, n = len(first_row), len(first_col)
res = np.zeros((m, n))

for i, val in enumerate(first_row):
    res += np.pad(np.eye(m-i, n-i) * val, ((0, i), (i, 0)), constant_values=0)

first_col[0] = 0
for i, val in enumerate(first_col):
    res += np.pad(np.eye(m-i, n-i) * val, ((i, 0), (0, i)), constant_values=0)
res

array([[1., 2., 3.],
       [4., 1., 2.],
       [5., 4., 1.]])

In [786]:
arr = np.array([1, 2, 3, 4], dtype=np.int64)
arr.dtype = np.int16
display(arr)
arr.dtype = np.int32
display(arr)
arr.dtype = np.int64
display(arr)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=int16)

array([1, 0, 2, 0, 3, 0, 4, 0], dtype=int32)

array([1, 2, 3, 4])

In [787]:
arr1 = np.array([0, 1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8, 9])

display(np.hstack((arr1, arr2)))
display(np.vstack((arr1, arr2)))
display(np.dstack((arr1, arr2)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

In [788]:
arr = np.arange(0, 10)

arr = np.concat((arr[:4], arr[5:]))

display(arr)

np.insert(arr, arr.searchsorted(4), 4)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [789]:
struct_type = [('name', 'S20'), ('age', 'u1')]
data = [('Fasih', 19), ('Hamna', 17), ('Pallo', 14)]

stds = np.array(data, dtype=struct_type)
stds.sort(order='age')
stds = stds[::-1]
stds

array([(b'Fasih', 19), (b'Hamna', 17), (b'Pallo', 14)],
      dtype=[('name', 'S20'), ('age', 'u1')])

In [790]:
c = 4
[print(' '*(c-a) + '*' + ' '*(a*2 - 1) + '*'*(a != 0)) for a in map(int, '0' + str(int('1' * c)**2) + '0')]
c

    *
   * *
  *   *
 *     *
*       *
 *     *
  *   *
   * *
    *


4

In [791]:
arr1 = np.arange(0, 8).reshape(2, 2, 2)
arr2 = np.arange(10, 18).reshape(2, 2, 2)

display(arr1, arr2)

np.cross(arr1, arr2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

C:\Users\Dell\AppData\Local\Temp\ipykernel_19624\210574428.py:6: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(arr1, arr2)


array([[-10, -10],
       [-10, -10]])

In [792]:
display(np.cross([1, 2, 3], [1, 2, 4]))
display(np.dot([1, 2, 3], [1, 2, 4]))

array([ 2, -1,  0])

np.int64(17)

In [793]:
A = [[4, 2], [1, 1]]
b = [16, 7]

np.linalg.solve(A, b)

array([1., 6.])

In [794]:
# PANDAS NOW

df = pd.DataFrame({ 'person_id': [1, 2, 3], 'name': ['Fasih', 'Hamna', 'Pallo'] }).replace(to_replace='Fasih', value='FASIH')
df.insert(1, 'age', [19, 17, 14])
df.sort_values(by='age')

new_record = pd.DataFrame(columns=df.columns, data=[(4, 8, 'Sabih')])
new_record

pd.concat((df.iloc[:1], new_record, df.iloc[1:]), ignore_index=True, axis=0)


person_id  age   name
0          1   19  FASIH
1          4    8  Sabih
2          2   17  Hamna
3          3   14  Pallo

In [795]:
df = pd.read_csv('heart.csv')
df = df.drop(columns='sex')

df = df.head()
df2 = df.tail()
df.insert(0, 'name', ['Alice', 'Bob', 'Charlie', 'David', 'Eve'])

display(df)
display(df.drop(axis=1, labels=['target', 'thal', 'ca', 'exang']))
display(df.drop(axis='rows', labels=[2]))
display(df.reset_index(drop=False))

name  age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    Alice   52   0       125   212    0        1      168      0      1.0   
1      Bob   53   0       140   203    1        0      155      1      3.1   
2  Charlie   70   0       145   174    0        1      125      1      2.6   
3    David   61   0       148   203    0        1      161      0      0.0   
4      Eve   62   0       138   294    1        1      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
2      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

name  age  cp  trestbps  chol  fbs  restecg  thalach  oldpeak  slope
0    Alice   52   0       125   212    0        1      168      1.0      2
1      Bob   53   0       140   203    1        0      155      3.1      0
2  Charlie   70   0       145   174    0        1      125      2.6      0
3    David   61   0       148   203    0        1      161      0.0      2
4      Eve   62   0       138   294    1        1      106      1.9      1

name  age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0  Alice   52   0       125   212    0        1      168      0      1.0   
1    Bob   53   0       140   203    1        0      155      1      3.1   
3  David   61   0       148   203    0        1      161      0      0.0   
4    Eve   62   0       138   294    1        1      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

index     name  age  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0      0    Alice   52   0       125   212    0        1      168      0   
1      1      Bob   53   0       140   203    1        0      155      1   
2      2  Charlie   70   0       145   174    0        1      125      1   
3      3    David   61   0       148   203    0        1      161      0   
4      4      Eve   62   0       138   294    1        1      106      0   

   oldpeak  slope  ca  thal  target  
0      1.0      2   2     3       0  
1      3.1      0   0     3       0  
2      2.6      0   0     3       0  
3      0.0      2   1     3       0  
4      1.9      1   3     2       0

In [796]:
pd.concat((df, df2)).dropna(axis='columns', how='any')

age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  \
0   52   0       125   212    0        1      168      0      1.0      2   2   
1   53   0       140   203    1        0      155      1      3.1      0   0   
2   70   0       145   174    0        1      125      1      2.6      0   0   
3   61   0       148   203    0        1      161      0      0.0      2   1   
4   62   0       138   294    1        1      106      0      1.9      1   3   
0   52   0       125   212    0        1      168      0      1.0      2   2   
1   53   0       140   203    1        0      155      1      3.1      0   0   
2   70   0       145   174    0        1      125      1      2.6      0   0   
3   61   0       148   203    0        1      161      0      0.0      2   1   
4   62   0       138   294    1        1      106      0      1.9      1   3   

   thal  target  
0     3       0  
1     3       0  
2     3       0  
3     3       0  
4     2       0  
0     3       0  
1     3       0  
2     3       0  
3     3       0  
4     2       0

In [797]:

df = pd.read_csv('heart.csv').head()
df.insert(0, 'name', ['Alice', 'Bob', 'Charlie', 'David', 'Eve'])

def do_nan():
    for val in np.random.randint(0, 5, 2):
        df.loc[val, 'chol'] = np.nan

# display(df)
do_nan()
df['chol'] = df['chol'].fillna(df['chol'].mean()).astype(np.int32)

# df.to_csv('new_hearts.csv', index=False, header=True)
pd.read_csv('new_hearts.csv').set_index('name')

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
name                                                                           
Alice     52    1   0       125   233    0        1      168      0      1.0   
Bob       53    1   0       140   203    1        0      155      1      3.1   
Charlie   70    1   0       145   233    0        1      125      1      2.6   
David     61    1   0       148   203    0        1      161      0      0.0   
Eve       62    0   0       138   294    1        1      106      0      1.9   

         slope  ca  thal  target  
name                              
Alice        2   2     3       0  
Bob          0   0     3       0  
Charlie      0   0     3       0  
David        2   1     3       0  
Eve          1   3     2       0

In [851]:
import re

text = 'my email is: fhk.tcs@gmail.com. My friend\'s email is: friend@mail.test'

re.findall(r'(\w+(?:\.\w+)*@\w+\.\w+(?:\.\w+)*)', text)

AttributeError: 'list' object has no attribute 'groups'